name: AoC Badges Action update
on:
#  schedule:                                        # run workflow based on schedule
#    - cron: '30 11 1-25 12 *'                      # from the 1. December till 25. December every day at 11:30am (avoid load at full hours)

  workflow_dispatch:                               # allow to manually start the workflow 

  push:                                            #  Run on push, be carefull with this setting 
                                                   # as the workflow should only be triggered at a rate lower than
                                                   # 4 times a hour to keep traffic on aoc site low 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                # clones your repo

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}     # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain

          # Optional inputs  
          year: 2024                                                                                            # The year for which stats should be retrieved
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Stars%202024%20â­-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2024%20day%20ðŸ“…-)[0-9]+(?=-blue)'                   # Regular expression that finds the content of the day badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2024%20days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.
      
      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update AoC badges
          file_pattern: README.md

#         Optional inputs:
#         
#         year: 2021                                                                                     # The year for which stats should be retrieved
#         leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
#         file: 'README.md'                                                                              # The file that contains the badges
#         dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20ðŸ“…-)[0-9]+(?=-blue)'                   # Regular expression that finds the content of the day badge in your file.
#         starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
#         daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.
#
#         more info: https://github.com/marketplace/actions/aoc-badges